### ISSUE TITLE
Just showing data for one Application

### ISSUE THREAD

**Issue by bigardone** [martyjs/marty-devtools#12]
Hi!
After upgrading to v0.10 and using the new **ApplicationContainers** I've created two different ApplicationContainers for two independent Applications. Everything works fine but the Chrome extension only shows Actions and Stores from the last rendered...

**Comment by jhollingworth** [comment]
Damn, I was hoping no one would do that! Currently application will only handle the latest instance created. I need to add support for visualising multiple application instances

**Comment by bigardone** [comment]
hahaha sorry man! Just coincided I'm developing an app where I need to have two independent applications :)

**Comment by jhollingworth** [comment]
No problem, It's going to be useful for debugging isomorphic apps so been on my to do list for a while. Will try and get to this asap
