### ISSUE TITLE
Non json-serializable data in actions/store.

### ISSUE THREAD

**Issue by quazzie** [martyjs/marty-devtools#13]
I get spammed with errors about "failed to post message: {...} Converting circular structure to JSON"
I send a youtube iframe player object through an action and save it in a store.
Now i can't use the dev-tools :\

**Comment by jhollingworth** [comment]
Do [serializers](http://martyjs.org/guides/developer-tools/index.html#serializers) help?

**Comment by quazzie** [comment]
I'll check tonight. Thanks!
