### ISSUE TITLE
Uncaught TypeError: Cannot set property 'devtoolsEnabled' of undefined

### ISSUE THREAD

**Issue by scottwernervt** [martyjs/marty-devtools#3]
I am getting the following error on Windows 7 (Google Chrome 40.0.2214.93 m) and Arch Linux (Chromium 40.0.2214.93 64-bit):

``` javascript
Uncaught TypeError: Cannot set property 'devtoolsEnabled' of undefined
chrome-extension://fifcikknnbggajppebgolpkaambnkpae/app/content/martyObserver.js
```

``` javascript

/** @jsx React.DOM */
'use strict';

var React = require('react');
var Marty = require('marty');
var Router = require('./router');

window.React = React; // For React Developer Tools
window.Marty = Marty; // For Marty Developer Tools

Router.run(function (Handler, state) {
    React.render(<Handler {...state.params} />, document.body);
});
```

Since the error is happening on both machines, I am wondering if it is related to how I am developing with gulp with browserSync. React extension is working.

**Comment by jhollingworth** [comment]
Hey, sorry thats a versioning problem. If you update to the latest version of Marty (v0.8.6) it should go away. I should have bumped the version for that change, my bad

**Comment by jhollingworth** [comment]
Marty DevTools v0.8.7 (Currently be published, should be about an hour) has resolved this issue. You should also upgrade to Marty v0.8.7

**Comment by scottwernervt** [comment]
Updating Marty DevTools and Marty solved it, thanks!
