### ISSUE TITLE
Problems with other things using postMessage

### ISSUE THREAD

**Issue by maddie927** [martyjs/marty-devtools#4]
Plugin does not work when Facebook's sdk is loaded.  sdk.js spews warnings about expecting a string but receiving an object and the Marty devtools tab is blank.  Some actions blow up serializing for postMessage that work fine when marty-devtools is off.

**Comment by dariocravero** [comment]
:+1: on this

**Comment by jhollingworth** [comment]
I've just published Marty v0.8.11 resolves this issue. The latest version of Marty DevTools (v0.8.11) should be processed in the hour which will make sure this doesn't happen again. Sorry for the delay in fixing this bug!
