### ISSUE TITLE
Warnings in Chrome console

### ISSUE THREAD

**Issue by optilude** [martyjs/marty-devtools#5]
When I load the Marty developer tools, I get a range of errors in the Chrome console:

![screen shot 2015-02-13 at 23 12 46](https://cloud.githubusercontent.com/assets/160906/6196928/f5d5c6a8-b3d5-11e4-861e-521c473092cb.png)

**Comment by optilude** [comment]
I'm sure that's cool and thanks again for the super-quick response, but turning off the logging doesn't feel like addressing the underlying issue :)

**Comment by jhollingworth** [comment]
Completely agree :) But there are two problems here:
1. The devtools logs shouldn't be logged to the console outside of development of the plugin
2. I've been misusing React and need to fix those issues

The former has impact on people right now so wanted to fix asap (I should have done it a while ago). The latter has no immediate impact on end users so can wait a couple of days  :)

**Comment by jhollingworth** [comment]
That said, I will keep this open until those warnings are fixed

**Comment by jhollingworth** [comment]
Warnings were fixed by #7. Will be released in a day or two
