### ISSUE TITLE
Unable to expand store object

### ISSUE THREAD

**Issue by imjared** [martyjs/marty-devtools#6]
Despite having a dropdown arrow, I'm unable to expand the store object: http://cl.ly/3w1Z181a192r. Single clicks do nothing and double clicks make the arrow disappear.

**Comment by jhollingworth** [comment]
Sorry for the delay on this. I've finally tracked this bug down and will be releasing the fix with the Marty v0.9 release

**Comment by jhollingworth** [comment]
Fixed by #7. Will be released in a day or two
